grails-app/domain/fr/mbds/tp/Game.groovy
package fr.mbds.tp

class Game {

    User winner
    User looser
    Integer winnerScore = 0
    Integer looserScore = 0

    Date dateCreated

    static constraints = {
        winner nullable: false
        looser nullable: false
        winnerScore nullable: false
        looserScore nullable: false
    }
}

grails-app/views/index/index.gsp
<!doctype html>
<html>
<head>
    <meta name="layout" content="main"/>
    <title>Welcome to Grails</title>
</head>
<body>
    <content tag="nav">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Application Status <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><a href="#">Environment: ${grails.util.Environment.current.name}</a></li>
                <li><a href="#">App profile: ${grailsApplication.config.grails?.profile}</a></li>
                <li><a href="#">App version:
                    <g:meta name="info.app.version"/></a>
                </li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Grails version:
                    <g:meta name="info.app.grailsVersion"/></a>
                </li>
                <li><a href="#">Groovy version: ${GroovySystem.getVersion()}</a></li>
                <li><a href="#">JVM version: ${System.getProperty('java.version')}</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Reloading active: ${grails.util.Environment.reloadingAgentEnabled}</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Artefacts <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <li><a href="#">Controllers: ${grailsApplication.controllerClasses.size()}</a></li>
                <li><a href="#">Domains: ${grailsApplication.domainClasses.size()}</a></li>
                <li><a href="#">Services: ${grailsApplication.serviceClasses.size()}</a></li>
                <li><a href="#">Tag Libraries: ${grailsApplication.tagLibClasses.size()}</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Installed Plugins <span class="caret"></span></a>
            <ul class="dropdown-menu">
                <g:each var="plugin" in="${applicationContext.getBean('pluginManager').allPlugins}">
                    <li><a href="#">${plugin.name} - ${plugin.version}</a></li>
                </g:each>
            </ul>
        </li>
    </content>

    <div class="svg" role="presentation">
        <div class="grails-logo-container">
            <asset:image src="grails-cupsonly-logo-white.svg" class="grails-logo"/>
        </div>
    </div>

    <div id="content" role="main">
        <section class="row colset-2-its">
            <h1>Scores</h1>

            <table>
                <tr>
                    <th>Winner</th>
                    <th>Winner Score</th>
                    <th>Game ID</th>
                    <th>Looser Score</th>
                    <th>Looser</th>
                </tr>
                <g:each in="${gameList}" var="game">
                    <tr>
                        <td><a href="/mbdstp/user/show/${game.winner.id}">${game.winner.username}</a></td>
                        <td style="color:SteelBlue;">${game.winnerScore}</td>
                        <td><a href="/mbdstp/game/show/${game.id}">${game.id}</a></td>
                        <td style="color:OrangeRed;">${game.looserScore}</td>
                        <td><a href="/mbdstp/user/show/${game.looser.id}">${game.looser.username}</a></td>
                    </tr>
                </g:each>
            </table>

        </section>
    </div>

</body>
</html>